export const GET_LOCK = 'RA/GET_LOCK';
export const GET_LOCK_LOADING = 'RA/GET_LOCK_LOADING';
export const GET_LOCK_SUCCESS = 'RA/GET_LOCK_SUCCESS';
export const GET_LOCK_FAILURE = 'RA/GET_LOCK_FAILURE';

export const GET_LOCKS = 'RA/GET_LOCKS';
export const GET_LOCKS_LOADING = 'RA/GET_LOCKS_LOADING';
export const GET_LOCKS_SUCCESS = 'RA/GET_LOCKS_SUCCESS';
export const GET_LOCKS_FAILURE = 'RA/GET_LOCKS_FAILURE';

export const LOCK = 'RA/LOCK';
export const LOCK_LOADING = 'RA/LOCK_LOADING';
export const LOCK_SUCCESS = 'RA/LOCK_SUCCESS';
export const LOCK_FAILURE = 'RA/LOCK_FAILURE';

export const UNLOCK = 'RA/UNLOCK';
export const UNLOCK_LOADING = 'RA/UNLOCK_LOADING';
export const UNLOCK_SUCCESS = 'RA/UNLOCK_SUCCESS';
export const UNLOCK_FAILURE = 'RA/UNLOCK_FAILURE';
