import fakeRestProvider from 'ra-data-fakerest';
export default fakeRestProvider({
    songs: [
        {
            id: 1,
            rank: 1,
            artist: 'Bob Dylan',
            title: 'Like a Rolling Stone',
            writer: 'Bob Dylan',
            producer: 'Tom Wilson',
            released: new Date('1965-07-01'),
            recordCompany: 'Columbia',
        },
        {
            id: 2,
            rank: 2,
            artist: 'The Rolling Stones',
            title: '(I Can’t Get No) Satisfaction',
            writer: 'Mick Jagger, Keith Richards',
            producer: 'Andrew Loog Oldham',
            released: new Date('1965-05-01'),
            recordCompany: 'London',
        },
        {
            id: 3,
            rank: 3,
            artist: 'John Lennon',
            title: 'Imagine',
            writer: 'John Lennon',
            producer: 'Lennon, Phil Spector, Yoko Ono',
            released: new Date('1971-10-01'),
            recordCompany: 'Apple',
        },
        {
            id: 4,
            rank: 4,
            artist: 'Marvin Gaye',
            title: 'What’s Going On',
            writer: 'Gaye, Renaldo Benson, Al Cleveland',
            producer: 'Gaye',
            released: new Date('1971-02-01'),
            recordCompany: 'Tamla',
        },
        {
            id: 5,
            rank: 5,
            artist: 'Aretha Franklin',
            title: 'Respect',
            writer: 'Otis Redding',
            producer: 'Jerry Wexler',
            released: new Date('1967-04-01'),
            recordCompany: 'Atlantic',
        },
        {
            id: 6,
            rank: 6,
            artist: 'The Beach Boys',
            title: 'Good Vibrations',
            writer: 'Brian Wilson, Mike Love',
            producer: 'Brian Wilson',
            released: new Date('1966-10-01'),
            recordCompany: 'Capitol',
        },
        {
            id: 7,
            rank: 7,
            artist: 'Chuck Berry',
            title: 'Johnny B. Goode',
            writer: 'Chuck Berry',
            producer: 'Leonard and Phil Chess',
            released: new Date('1958-04-01'),
            recordCompany: 'Chess',
        },
        {
            id: 8,
            rank: 8,
            artist: 'The Beatles',
            title: 'Hey Jude',
            writer: 'John Lennon, Paul McCartney',
            producer: 'George Martin',
            released: new Date('1968-08-01'),
            recordCompany: 'Apple',
        },
        {
            id: 9,
            rank: 9,
            artist: 'Nirvana',
            title: 'Smells Like Teen Spirit',
            writer: 'Kurt Cobain',
            producer: 'Butch Vig',
            released: new Date('1991-09-01'),
            recordCompany: 'DGC',
        },
        {
            id: 10,
            rank: 10,
            artist: 'Ray Charles',
            title: 'What’d I Say',
            writer: 'Ray Charles',
            producer: 'Ahmet Ertegun, Jerry Wexler',
            released: new Date('1959-06-01'),
            recordCompany: 'Atlantic',
        },
    ],
}, true);
