"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.REMOVE_UNSAVED_CHILD_NODE = exports.ADD_UNSAVED_CHILD_NODE = exports.REMOVE_UNSAVED_ROOT_NODE = exports.ADD_UNSAVED_ROOT_NODE = exports.CREATE_RECORD_FROM_NODE = exports.POPULATE_RECORDS_FROM_NODES = exports.CRUD_DELETE_BRANCH_FAILURE = exports.CRUD_DELETE_BRANCH_SUCCESS = exports.CRUD_DELETE_BRANCH_LOADING = exports.CRUD_DELETE_BRANCH = exports.CRUD_ADD_CHILD_NODE_FAILURE = exports.CRUD_ADD_CHILD_NODE_SUCCESS = exports.CRUD_ADD_CHILD_NODE_LOADING = exports.CRUD_ADD_CHILD_NODE = exports.CRUD_ADD_ROOT_NODE_FAILURE = exports.CRUD_ADD_ROOT_NODE_SUCCESS = exports.CRUD_ADD_ROOT_NODE_LOADING = exports.CRUD_ADD_ROOT_NODE = exports.CRUD_MOVE_AS_NTH_SIBLING_OF_FAILURE = exports.CRUD_MOVE_AS_NTH_SIBLING_OF_SUCCESS = exports.CRUD_MOVE_AS_NTH_SIBLING_OF_LOADING = exports.CRUD_MOVE_AS_NTH_SIBLING_OF = exports.CRUD_MOVE_AS_NTH_CHILD_OF_FAILURE = exports.CRUD_MOVE_AS_NTH_CHILD_OF_SUCCESS = exports.CRUD_MOVE_AS_NTH_CHILD_OF_LOADING = exports.CRUD_MOVE_AS_NTH_CHILD_OF = exports.CRUD_GET_CHILD_NODES_FAILURE = exports.CRUD_GET_CHILD_NODES_SUCCESS = exports.CRUD_GET_CHILD_NODES_LOADING = exports.CRUD_GET_CHILD_NODES = exports.CRUD_GET_ROOT_NODES_FAILURE = exports.CRUD_GET_ROOT_NODES_SUCCESS = exports.CRUD_GET_ROOT_NODES_LOADING = exports.CRUD_GET_ROOT_NODES = exports.CRUD_GET_TREE_FAILURE = exports.CRUD_GET_TREE_SUCCESS = exports.CRUD_GET_TREE_LOADING = exports.CRUD_GET_TREE = exports.expandNode = exports.EXPAND_NODE = exports.changeExpandedNodes = exports.CHANGE_EXPANDED_NODES = void 0;
exports.CHANGE_EXPANDED_NODES = 'RA/TREE/CHANGE_EXPANDED_NODES';
exports.changeExpandedNodes = function (resource, nodeIds) { return ({
    type: exports.CHANGE_EXPANDED_NODES,
    payload: nodeIds,
    meta: { resource: resource },
}); };
exports.EXPAND_NODE = 'RA/TREE/EXPAND_NODE';
exports.expandNode = function (resource, nodeId) { return ({
    type: exports.EXPAND_NODE,
    payload: nodeId,
    meta: { resource: resource },
}); };
exports.CRUD_GET_TREE = 'RA/CRUD_GET_TREE';
exports.CRUD_GET_TREE_LOADING = 'RA/CRUD_GET_TREE_LOADING';
exports.CRUD_GET_TREE_SUCCESS = 'RA/CRUD_GET_TREE_SUCCESS';
exports.CRUD_GET_TREE_FAILURE = 'RA/CRUD_GET_TREE_FAILURE';
exports.CRUD_GET_ROOT_NODES = 'RA/CRUD_GET_ROOT_NODES';
exports.CRUD_GET_ROOT_NODES_LOADING = 'RA/CRUD_GET_ROOT_NODES_LOADING';
exports.CRUD_GET_ROOT_NODES_SUCCESS = 'RA/CRUD_GET_ROOT_NODES_SUCCESS';
exports.CRUD_GET_ROOT_NODES_FAILURE = 'RA/CRUD_GET_ROOT_NODES_FAILURE';
exports.CRUD_GET_CHILD_NODES = 'RA/CRUD_GET_CHILD_NODES';
exports.CRUD_GET_CHILD_NODES_LOADING = 'RA/CRUD_GET_CHILD_NODES_LOADING';
exports.CRUD_GET_CHILD_NODES_SUCCESS = 'RA/CRUD_GET_CHILD_NODES_SUCCESS';
exports.CRUD_GET_CHILD_NODES_FAILURE = 'RA/CRUD_GET_CHILD_NODES_FAILURE';
exports.CRUD_MOVE_AS_NTH_CHILD_OF = 'RA/CRUD_MOVE_AS_NTH_CHILD_OF';
exports.CRUD_MOVE_AS_NTH_CHILD_OF_LOADING = 'RA/CRUD_MOVE_AS_NTH_CHILD_OF_LOADING';
exports.CRUD_MOVE_AS_NTH_CHILD_OF_SUCCESS = 'RA/CRUD_MOVE_AS_NTH_CHILD_OF_SUCCESS';
exports.CRUD_MOVE_AS_NTH_CHILD_OF_FAILURE = 'RA/CRUD_MOVE_AS_NTH_CHILD_OF_FAILURE';
exports.CRUD_MOVE_AS_NTH_SIBLING_OF = 'RA/CRUD_MOVE_AS_NTH_SIBLING_OF';
exports.CRUD_MOVE_AS_NTH_SIBLING_OF_LOADING = 'RA/CRUD_MOVE_AS_NTH_SIBLING_OF_LOADING';
exports.CRUD_MOVE_AS_NTH_SIBLING_OF_SUCCESS = 'RA/CRUD_MOVE_AS_NTH_SIBLING_OF_SUCCESS';
exports.CRUD_MOVE_AS_NTH_SIBLING_OF_FAILURE = 'RA/CRUD_MOVE_AS_NTH_SIBLING_OF_FAILURE';
exports.CRUD_ADD_ROOT_NODE = 'RA/CRUD_ADD_ROOT_NODE';
exports.CRUD_ADD_ROOT_NODE_LOADING = 'RA/CRUD_ADD_ROOT_NODE_LOADING';
exports.CRUD_ADD_ROOT_NODE_SUCCESS = 'RA/CRUD_ADD_ROOT_NODE_SUCCESS';
exports.CRUD_ADD_ROOT_NODE_FAILURE = 'RA/CRUD_ADD_ROOT_NODE_FAILURE';
exports.CRUD_ADD_CHILD_NODE = 'RA/CRUD_ADD_CHILD_NODE';
exports.CRUD_ADD_CHILD_NODE_LOADING = 'RA/CRUD_ADD_CHILD_NODE_LOADING';
exports.CRUD_ADD_CHILD_NODE_SUCCESS = 'RA/CRUD_ADD_CHILD_NODE_SUCCESS';
exports.CRUD_ADD_CHILD_NODE_FAILURE = 'RA/CRUD_ADD_CHILD_NODE_FAILURE';
exports.CRUD_DELETE_BRANCH = 'RA/CRUD_DELETE_BRANCH';
exports.CRUD_DELETE_BRANCH_LOADING = 'RA/CRUD_DELETE_BRANCH_LOADING';
exports.CRUD_DELETE_BRANCH_SUCCESS = 'RA/CRUD_DELETE_BRANCH_SUCCESS';
exports.CRUD_DELETE_BRANCH_FAILURE = 'RA/CRUD_DELETE_BRANCH_FAILURE';
exports.POPULATE_RECORDS_FROM_NODES = 'RA/TREE/POPULATE_RECORDS_FROM_NODES';
exports.CREATE_RECORD_FROM_NODE = 'RA/TREE/CREATE_RECORD_FROM_NODE';
exports.ADD_UNSAVED_ROOT_NODE = 'RA/TREE/ADD_UNSAVED_ROOT_NODE';
exports.REMOVE_UNSAVED_ROOT_NODE = 'RA/TREE/REMOVE_UNSAVED_ROOT_NODE';
exports.ADD_UNSAVED_CHILD_NODE = 'RA/TREE/ADD_UNSAVED_CHILD_NODE';
exports.REMOVE_UNSAVED_CHILD_NODE = 'RA/TREE/REMOVE_UNSAVED_CHILD_NODE';
