import addLocksMethodsBasedOnALockResource from './addLocksMethodsBasedOnALockResource';
import addRealTimeMethodsBasedOnApiPlatform from './addRealTimeMethodsBasedOnApiPlatform';
import addRealTimeMethodsBasedOnMercure from './addRealTimeMethodsBasedOnMercure';
import addRealTimeMethodsInLocalBrowser from './addRealTimeMethodsInLocalBrowser';
export { addLocksMethodsBasedOnALockResource, addRealTimeMethodsBasedOnApiPlatform, addRealTimeMethodsBasedOnMercure, addRealTimeMethodsInLocalBrowser, };
